name: tecnologia-web
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    image: jenkins-jdk-17
    networks:
      - proyectos-app
    ports:
      - "8081:8080"
      - "50000:50000"
    restart: always
    user: root
    volumes:
      - jenkins_home:/var/jenkins_home
      - \\.\pipe\docker_engine:\\.\pipe\docker_engine
networks:
  proyectos-app:
    name: tecnologia-web_proyectos-app
volumes:
  jenkins_home:
    name: jenkins_home
