version: '3.8'
services: 
  jenkins:
    build:
      context: .
    image: jenkins-jdk-17
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    restart: always
    networks:
      - proyectos-app

networks:
  proyectos-app:

volumes:
  jenkins_home:
    name: jenkins_home
