version: "3.7"
services: 
   jenkins:
    build:
      context: .
    ports:
      - "8081:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    restart: always
    networks:
      - proyectos-app

  monolito:
    container_name: monolito
    image: monolito:v1
    build: 
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "4001"
    networks:
      - proyectos-app
    pull_policy: never

  monolito-2:
    container_name: monolito-2
    image: monolito:v1
    build: 
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "4001"
    networks:
      - proyectos-app
    pull_policy: never

  monolito-3:
    container_name: monolito-3
    image: monolito:v1
    build: 
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "4001"
    networks:
      - proyectos-app
    pull_policy: never

  monolito-4:
    container_name: monolito-4
    image: monolito:v1
    build: 
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "4001"
    networks:
      - proyectos-app
    pull_policy: never

  balanceador-carga:
    container_name: balanceador-carga
    build:
      context: ./src/balancer
      dockerfile: Dockerfile
    ports:
      - "4002:80"
    networks:
      - proyectos-app
    pull_policy: never


networks:
  proyectos-app:

volumes:
  jenkins_home: {}
    
    