version: "3.7"
services: 
  monolito:
    container_name: monolito
    image: monolito:v1
    build: 
      context: .
    ports:
      - "4000:4000"
    networks:
      - proyectos-app

networks:
  proyectos-app:
    
    